pipeline {
  agent any

  environment {
    CYPRESS_PROJECT_ID = credentials('CYPRESS_PROJECT_ID')
    CYPRESS_RECORD_KEY = credentials('CYPRESS_RECORD_KEY')
  }

  stages {
    stage('install dependencies') {
      steps {
        sh "npm run e2e:record --first=${env.BUILD_ID}"
      }
    }
  }
}
