pipeline {
  agent any

  environment {
    CYPRESS_PROJECT_ID = credentials('CYPRESS_PROJECT_ID')
    CYPRESS_RECORD_KEY = credentials('CYPRESS_RECORD_KEY')
  }

  stages {
    stage('install dependencies') {
      steps {
        echo "Running build ${env.BUILD_ID} on ${env.JENKINS_URL}"
        sh 'npm ci'
      }
    }

    stage('verify cypress') {
      steps {
        sh '$(npm bin)/cypress cache path'
        sh '$(npm bin)/cypress cache list'
        sh '$(npm bin)/cypress verify'
      }
    }
  }
}
