pipeline {
  agent any

  environment {
    CYPRESS_PROJECT_ID = credentials('CYPRESS_PROJECT_ID')
    CYPRESS_RECORD_KEY = credentials('CYPRESS_RECORD_KEY')
    HOME = '.'
  }

  stages {
    stage('build') {
      steps {
        sh 'npm ci'
      }
    }
  }
}