pipeline {
  agent any

  environment {
    CYPRESS_PROJECT_ID = credentials('CYPRESS_PROJECT_ID')
    CYPRESS_RECORD_KEY = credentials('CYPRESS_RECORD_KEY')
    HOME = '.'
  }

  stages {

    stage('verify cypress') {
      steps {
        sh '$(npm bin)/cypress cache path'
        sh '$(npm bin)/cypress cache list'
        sh '$(npm bin)/cypress verify'
      }
    }

    stage('execute E2E') {
      steps {
        sh "npm run e2e:record"
      }
    }
  }
}