pipeline {
  agent any

  environment {
    CYPRESS_PROJECT_ID = credentials('CYPRESS_PROJECT_ID')
    CYPRESS_RECORD_KEY = credentials('CYPRESS_RECORD_KEY')
  }

  stages {

    stage('execute E2E parallel') {
      failFast true
      parallel {
        stage('E2E tests A') {
          steps {
            sh "npx cypress run --record --group e2e-specs-cypress-12345 --ci-build-id ${env.BUILD_ID} --parallel"
          }
        }
      }
    }
  }

  post {
    always {
      echo 'Stopping local server'
      sh 'pkill -f http-server'
    }
  }
}