pipeline {
  agent {
    docker {
      image 'cypress/base:10'
    }
  }

  stages {
    stage('build') {
      steps {
        sh 'npm ci'
      }
    }

    stage('cypress parallel tests') {
      environment {
        CYPRESS_PROJECT_ID = credentials('CYPRESS_PROJECT_ID')
        CYPRESS_RECORD_KEY = credentials('CYPRESS_RECORD_KEY')
      }

      parallel {
        stage('E2E tests') {
          steps {
            echo "Running build ${env.BUILD_ID}"
            sh "npm run e2e:record:parallel"
          }
        }
      }
    }
  }
}