pipeline {
  agent any

  environment {
    LT_USERNAME = credentials('LT_USERNAME')
    LT_ACCESS_KEY = credentials('LT_ACCESS_KEY')
  }

  stages {

    stage('execute E2E') {
      steps {
        sh "echo npm run ci:lambdatest --build_name=${env.BUILD_ID}"
      }
    }
  }
}
