pipeline {
  agent any

  environment {
    LT_USERNAME = credentials('LT_USERNAME')
    LT_ACCESS_KEY = credentials('LT_ACCESS_KEY')
  }

  stages {

    stage('execute exiwt') {
      steps {
        error 'sdds'
      }
    }

    stage('execute exit') {
      steps {
       echo "${currentBuild.currentResult}";
      }
    }
  }
}