def myVariable = "dsds"
pipeline {
  agent any

  environment {
    LT_USERNAME = credentials('LT_USERNAME')
    LT_ACCESS_KEY = credentials('LT_ACCESS_KEY')
  }

  stages {

    stages {
        stage("Using curl example") {
            steps {
                script {
                    final String url = "https://jsonplaceholder.typicode.com/posts"

                    final String response = sh(script: "curl -s $url", returnStdout: true).trim()

                    echo response
                }
            }
        }
    }
  }
}