name: Github action cypress integration
on: push

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      - run: |
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify

  cypress-run-chrome:
    needs: [install]
    name: E2E on Node v${{ matrix.node }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16]
        browser: [chrome]
        machines: [1, 2, 3, 4]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Cypress run chrome
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          headless: true
          browser: chrome
          group: browser-test-${{ matrix.node }}-${{ matrix.browser }}
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}

      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@master
        with:
          name: videos
          path: cypress/videos
          if-no-files-found: ignore

  cypress-run-electron:
    needs: [install]
    name: E2E on Node v${{ matrix.node }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16]
        browser: [electron]
        machines: [1, 2, 3, 4]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run Electron
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          headless: true
          browser: electron
          group: browser-test-${{ matrix.node }}-${{ matrix.browser }}
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}

      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@master
        with:
          name: videos
          path: cypress/videos
          if-no-files-found: ignore

  cypress-run-firefox:
    needs: [install]
    name: E2E on Node v${{ matrix.node }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16]
        browser: [firefox]
        machines: [1, 2, 3, 4]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run Firefox
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          headless: true
          browser: firefox
          group: browser-test-${{ matrix.node }}-${{ matrix.browser }}
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}

      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@master
        with:
          name: videos
          path: cypress/videos
          if-no-files-found: ignore
