name: Lambdatest cypress integration
on: push

jobs:
  build:
    name: E2E on Node v${{ matrix.node }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node: [16]

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v3.0.0

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - run: npm ci
      - run: npm run build
      - run: npm install -g lambdatest-cypress-cli
      - run: nohup npm run start-server &

      - name: Execute lambdatest cli
        run: npm run ci:lambdatest --build_name=${{ github.head_ref }}-${{ github.run_id }}
        shell: bash -e {0}
        env:
          LT_USERNAME: ${{secrets.LT_USERNAME}}
          LT_ACCESS_KEY: ${{secrets.LT_ACCESS_KEY}}
