name: demo integration
on: push

jobs:
  build:
    name: demo
    runs-on: ubuntu-latest

    steps:
      - name: Execute lambdatest cli
        run: |
          if [ ${{npm --version}} -ne 0 ]; then
              echo "command failed"-$?
          else
              echo "command success"-$?
          fi
