name: Context testing
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.stepstatus.outputs.status }}
    steps:
      - id: stepstatus
        run: |
          echo "::set-output name=status::$(git --version)"

  job2:
    runs-on: ubuntu-latest
    needs: dump_contexts_to_log
    steps:
      - run: echo ${{needs.dump_contexts_to_log.outputs.output1}}
