name: demo integration
on: push

jobs:
  build:
    name: demo
    runs-on: ubuntu-latest

    steps:
      - name: Execute lambdatest cli
        run: |
          npm run ci:lambdatest --build_name="jsdhdh"
          if [ $? -ne 0 ]; then
            echo "command failed"-$?
            exit 1;
          fi
