name: Github action cypress integration
on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - run: npm ci
