name: demo integration
on: push

jobs:
  build:
    name: demo
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        run: |
          if npm --version; then
              echo "command succeeded"
          else
              echo "command failed"
          fi
