name: Github action cypress integration
on: workflow_dispatch

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/base:16.14.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      - run: |
          cat /etc/os-release
