name: Context testing
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'develop'

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: |
          echo '${{ toJSON(github) }}'
          echo $GITHUB_REPOSITORY
