name: demo integration
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'develop'

jobs:
  build:
    name: demo
    runs-on: ubuntu-latest

    steps:
      - name: Execute lambdatest cli
        run: npm jhjdjh
