name: Github action cypress integration
on: push

jobs:
  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress.io
        uses: cypress-io/github-action@v2
