name: Lambdatest cypress integration

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm install -g lambdatest-cypress-cli
      - run: lambdatest-cypress run --s ./cypress/integration/*.spec.js
        env:
          LT_USERNAME: ${{secrets.LT_USERNAME}}
          LT_ACCESS_KEY: ${{secrets.LT_ACCESS_KEY}}
